version: "3.8"

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    command:
      - run
      - --enable-api
      - --cors
      - "*"

  action_server:
    build:
      context: .
      dockerfile: actions/Dockerfile
    ports:
      - "5055:5055"
