services:
  - type: web
    name: rasa-actions
    env: docker
    plan: free
    dockerfilePath: actions/Dockerfile
    envVars:
      - key: PORT
        value: 5055
    startCommand: rasa run actions --port 5055

  - type: web
    name: rasa-server
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: ACTIONS_ENDPOINT
        value: https://rasa-actions.onrender.com