services:
  - type: web
    name: rasa-server
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
    startCommand: rasa run --enable-api --cors "*" --port 8000

  - type: web
    name: rasa-actions
    env: docker
    dockerfilePath: actions/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 5055
    startCommand: rasa run actions